name: macro_calculator
description: A new Flutter project.
version: 2.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  horizontal_picker: ^1.0.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  dynamic_theme: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
        - asset: fonts/Quicksand/Quicksand-Light.ttf
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
        - asset: fonts/Quicksand/Quicksand-SemiBold.ttf

    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
        - asset: fonts/poppins/Poppins-Black.ttf
